### ISSUE TITLE
Why stop development?

### ISSUE THREAD

**Issue by oHeyDeniis** [KalmeMarq/json-ui-editor#1]
Why is it a "useless" project? Me and other dev friends who use ui think it's an amazing project, is there already something similar to what you started?

**Comment by KalmeMarq** [comment]
There isn't any thing like this, mostly bc it's not easy to do. I stopped bc it feels useless. If you want to test UI stuff you can simply use the start screen for it. Minecraft doesn't take that long to load. I still want to the a json ui mod for java but right now I have other things I want to do... like sleeping and stuff.
